// Entire CLI plugin for OpenCode
// Auto-generated by `entire enable --agent opencode`
// Do not edit manually — changes will be overwritten on next install.
// Requires Bun runtime (used by OpenCode's plugin system for loading ESM plugins).
import type { Plugin } from "@opencode-ai/plugin";

export const EntirePlugin: Plugin = async ({ $, directory }) => {
  const ENTIRE_CMD = "entire";
  // Track seen user messages to fire turn-start only once per message
  const seenUserMessages = new Set<string>();
  // Track current session ID for message events (which don't include sessionID)
  let currentSessionID: string | null = null;
  // Track the model used by the most recent assistant message
  let currentModel: string | null = null;
  // In-memory store for message metadata (role, tokens, etc.)
  const messageStore = new Map<string, any>();
  // Track completed assistant messages to avoid firing turn-end twice for same message
  const completedAssistantMessages = new Set<string>();
  // Track whether a turn is active (turn-start fired, turn-end not yet)
  let turnActive = false;

  /**
   * Pipe JSON payload to an entire hooks command (async).
   * Errors are logged but never thrown — plugin failures must not crash OpenCode.
   */
  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload);
      await $`echo ${json} | ${ENTIRE_CMD} hooks opencode ${hookName}`
        .quiet()
        .nothrow();
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  /**
   * Synchronous variant for hooks that fire near process exit (turn-end, session-end).
   * `opencode run` breaks its event loop on the same session.status idle event that
   * triggers turn-end. The async callHook would be killed before completing.
   * Bun.spawnSync blocks the event loop, preventing exit until the hook finishes.
   */
  function callHookSync(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload);
      Bun.spawnSync(["sh", "-c", `${ENTIRE_CMD} hooks opencode ${hookName}`], {
        cwd: directory,
        stdin: new TextEncoder().encode(json + "\n"),
        stdout: "ignore",
        stderr: "ignore",
      });
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  return {
    event: async ({ event }) => {
      switch (event.type) {
        case "session.created": {
          const session = (event as any).properties?.info;
          if (!session?.id) break;
          // Reset per-session tracking state when switching sessions.
          if (currentSessionID !== session.id) {
            seenUserMessages.clear();
            messageStore.clear();
            completedAssistantMessages.clear();
            turnActive = false;
            currentModel = null;
          }
          currentSessionID = session.id;
          await callHook("session-start", {
            session_id: session.id,
          });
          break;
        }

        case "message.updated": {
          const msg = (event as any).properties?.info;
          if (!msg) break;
          // Store message metadata (role, time, tokens, etc.)
          messageStore.set(msg.id, msg);
          // Track model from assistant messages
          if (msg.role === "assistant" && msg.modelID) {
            currentModel = msg.modelID;
          }
          // TURN-END DETECTION: assistant message with time.completed means the turn finished.
          // This fires synchronously within the prompt loop, BEFORE session.status idle,
          // avoiding the race condition where `opencode run` exits before the hook completes.
          if (
            msg.role === "assistant" &&
            msg.time?.completed > 0 &&
            !completedAssistantMessages.has(msg.id)
          ) {
            completedAssistantMessages.add(msg.id);
            const sessionID = msg.sessionID ?? currentSessionID;
            if (sessionID && turnActive) {
              turnActive = false;
              callHookSync("turn-end", {
                session_id: sessionID,
                model: msg.modelID ?? currentModel ?? "",
                message_id: msg.id ?? "",
              });
            }
          }
          break;
        }

        case "message.part.updated": {
          const part = (event as any).properties?.part;
          if (!part?.messageID) break;

          // Fire turn-start on the first text part of a new user message
          const msg = messageStore.get(part.messageID);
          if (
            msg?.role === "user" &&
            part.type === "text" &&
            !seenUserMessages.has(msg.id)
          ) {
            seenUserMessages.add(msg.id);
            turnActive = true;
            const sessionID = msg.sessionID ?? currentSessionID;
            if (sessionID) {
              await callHook("turn-start", {
                session_id: sessionID,
                prompt: part.text ?? "",
                model: currentModel ?? "",
              });
            }
          }
          break;
        }

        case "session.status": {
          // session.status idle was previously used for turn-end detection, but has a
          // race condition in `opencode run` mode: the process exits on the same idle
          // event before the async plugin handler completes. Turn-end is now detected
          // via message.updated (see above), which fires synchronously within the
          // prompt loop before the idle race window opens.
          //
          // See: https://github.com/anomalyco/opencode — session/status.ts, plugin/index.ts
          break;
        }

        case "session.compacted": {
          const sessionID = (event as any).properties?.sessionID;
          if (!sessionID) break;
          await callHook("compaction", {
            session_id: sessionID,
          });
          break;
        }

        case "session.deleted": {
          const session = (event as any).properties?.info;
          if (!session?.id) break;
          seenUserMessages.clear();
          messageStore.clear();
          completedAssistantMessages.clear();
          turnActive = false;
          currentSessionID = null;
          // Use sync variant: session-end may fire during shutdown.
          callHookSync("session-end", {
            session_id: session.id,
          });
          break;
        }

        case "server.instance.disposed": {
          // Fires when OpenCode shuts down (TUI close or `opencode run` exit).
          // session.deleted only fires on explicit user deletion, not on quit,
          // so this is the only reliable way to end sessions on exit.
          if (!currentSessionID) break;
          const sessionID = currentSessionID;
          // If a turn was active when the process exits (e.g., OpenCode crashed
          // mid-response), fire turn-end before session-end to save whatever
          // checkpoint data is available.
          if (turnActive) {
            turnActive = false;
            callHookSync("turn-end", {
              session_id: sessionID,
              model: currentModel ?? "",
            });
          }
          seenUserMessages.clear();
          messageStore.clear();
          completedAssistantMessages.clear();
          currentSessionID = null;
          currentModel = null;
          // Use sync variant: this is the last event before process exit.
          callHookSync("session-end", {
            session_id: sessionID,
          });
          break;
        }
      }
    },
  };
};
